# Generated by Django 4.2.4 on 2023-08-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupjoinrequest',
            options={'verbose_name': 'Group Join Request', 'verbose_name_plural': 'Group Join Requests'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='secretsantaassignment',
            options={'verbose_name': 'Secret Santa Assignment', 'verbose_name_plural': 'Secret Santa Assignments'},
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
