# Generated by Django 4.2.4 on 2023-08-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0002_alter_group_options_alter_groupjoinrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupjoinrequest',
            options={},
        ),
    ]
